export const WWN = {
  scores: {
    str: "WWN.scores.str.short",
    dex: "WWN.scores.dex.short",
    con: "WWN.scores.con.short",
    int: "WWN.scores.int.short",
    wis: "WWN.scores.wis.short",
    cha: "WWN.scores.cha.short",
  },
  roll_type: {
    result: "=",
    above: "≥",
    below: "≤"
  },
  saves: {
    evasion: "WWN.saves.evasion",
    mental: "WWN.saves.mental",
    physical: "WWN.saves.physical",
    luck: "WWN.saves.luck",
  },
  skills: {
    admin: "WWN.skills.administer",
    connect: "WWN.skills.connect",
    convince: "WWN.skills.convince",
    craft: "WWN.skills.craft",
    exert: "WWN.skills.exert",
    heal: "WWN.skills.heal",
    know: "WWN.skills.know",
    lead: "WWN.skills.lead",
    magic: "WWN.skills.magic",
    notice: "WWN.skills.notice",
    perform: "WWN.skills.perform",
    pray: "WWN.skills.pray",
    punch: "WWN.skills.punch",
    ride: "WWN.skills.ride",
    sail: "WWN.skills.sail",
    shoot: "WWN.skills.shoot",
    sneak: "WWN.skills.sneak",
    stab: "WWN.skills.stab",
    survive: "WWN.skills.survive",
    trade: "WWN.skills.trade",
    work: "WWN.skills.work"
  },
  skillDice: {
    "2d6": "2d6",
    "3d6kh2": "3d6",
    "4d6kh2": "4d6",
    "1d6": "1d6"
  },
  encumbLocation: {
    readied: "WWN.items.readied",
    stowed: "WWN.items.stowed",
    other: "WWN.items.other"
  },
  weightless: {
    never: "WWN.items.WeightlessNever",
    whenReadied: "WWN.items.WeightlessReadied",
    whenStowed: "WWN.items.WeightlessStowed"
  },
  armor: {
    unarmored: "WWN.armor.unarmored",
    light: "WWN.armor.light",
    medium: "WWN.armor.medium",
    heavy: "WWN.armor.heavy",
    shield: "WWN.armor.shield",
  },
  colors: {
    green: "WWN.colors.green",
    red: "WWN.colors.red",
    yellow: "WWN.colors.yellow",
    purple: "WWN.colors.purple",
    blue: "WWN.colors.blue",
    orange: "WWN.colors.orange",
    white: "WWN.colors.white"
  },
  languages: [
    "Trade Cant",
    "Ancient Vothian",
    "Old Vothian",
    "Modern Vothian",
    "Ancient Olok",
    "Brass Speech",
    "Ancient Lin",
    "Emedian",
    "Ancient Osrin",
    "Thurian",
    "Ancient Khalan",
    "Llaigisan",
    "Anak Speech",
    "Predecessant",
    "Abased",
    "Recurrent",
    "Deep Speech"
  ],
  tags: {
    melee: "WWN.items.Melee",
    missile: "WWN.items.Missile",
    SR: "WWN.items.SR",
    TH: "WWN.items.2H",
    AP: "WWN.items.AP",
    FX: "WWN.items.FX",
    L: "WWN.items.L",
    R: "WWN.items.R",
    LL: "WWN.items.LL",
    N: "WWN.items.N",
    PM: "WWN.items.PM",
    S: "WWN.items.S",
    SS: "WWN.items.SS",
    T: "WWN.items.T",
    CB: "WWN.items.CB"
  },
  tag_images: {
    melee: "systems/wwn/assets/melee.png",
    missile: "systems/wwn/assets/missile.png",
    SR: "systems/wwn/assets/slow_reload.png",
    TH: "systems/wwn/assets/twohanded.png",
    AP: "systems/wwn/assets/armor_piercing.png",
    FX: "systems/wwn/assets/fixed.png",
    L: "systems/wwn/assets/long.png",
    R: "systems/wwn/assets/reload.png",
    LL: "systems/wwn/assets/less_lethal.png",
    N: "systems/wwn/assets/numerous.png",
    PM: "systems/wwn/assets/precisely_murderous.png",
    S: "systems/wwn/assets/subtle.png",
    SS: "systems/wwn/assets/single_shot.png",
    T: "systems/wwn/assets/throwable.png",
    CB: "systems/wwn/assets/crossbow.png"
  },
  tag_desc: {
    melee: "WWN.items.desc.Melee",
    missile: "WWN.items.desc.Missile",
    SR: "WWN.items.desc.SR",
    TH: "WWN.items.desc.2H",
    AP: "WWN.items.desc.AP",
    FX: "WWN.items.desc.FX",
    L: "WWN.items.desc.L",
    R: "WWN.items.desc.R",
    LL: "WWN.items.desc.LL",
    N: "WWN.items.desc.N",
    PM: "WWN.items.desc.PM",
    S: "WWN.items.desc.S",
    SS: "WWN.items.desc.SS",
    T: "WWN.items.desc.T",
    CB: "WWN.items.desc.CB"
  },
  assetTypes: {
    cunning: "WWN.asset.cunning",
    force: "WWN.asset.force",
    wealth: "WWN.asset.wealth"
  },
  assetMagic: {
    none: "WWN.asset.magicNone",
    low: "WWN.asset.magicLow",
    medium: "WWN.asset.magicMedium",
    high: "WWN.asset.magicHigh",
  }
};