export const WWN = {
  scores: {
    str: "WWN.scores.str.long",
    int: "WWN.scores.int.long",
    dex: "WWN.scores.dex.long",
    wis: "WWN.scores.wis.long",
    con: "WWN.scores.con.long",
    cha: "WWN.scores.cha.long",
  },
  roll_type: {
    result: "=",
    above: "≥",
    below: "≤"
  },
  saves: {
    evasion: "WWN.saves.evasion",
    mental: "WWN.saves.mental",
    physical: "WWN.saves.physical",
    luck: "WWN.saves.luck",
  },
  skills: {
    admin: "WWN.skills.administer",
    connect: "WWN.skills.connect",
    convince: "WWN.skills.convince",
    craft: "WWN.skills.craft",
    exert: "WWN.skills.exert",
    heal: "WWN.skills.heal",
    know: "WWN.skills.know",
    lead: "WWN.skills.lead",
    magic: "WWN.skills.magic",
    notice: "WWN.skills.notice",
    perform: "WWN.skills.perform",
    pray: "WWN.skills.pray",
    punch: "WWN.skills.punch",
    ride: "WWN.skills.ride",
    sail: "WWN.skills.sail",
    shoot: "WWN.skills.shoot",
    sneak: "WWN.skills.sneak",
    stab: "WWN.skills.stab",
    survive: "WWN.skills.survive",
    trade: "WWN.skills.trade",
    work: "WWN.skills.work"
  },
  armor : {
    unarmored: "WWN.armor.unarmored",
    light: "WWN.armor.light",
    heavy: "WWN.armor.heavy",
    shield: "WWN.armor.shield",
  },
  colors: {
    green: "WWN.colors.green",
    red: "WWN.colors.red",
    yellow: "WWN.colors.yellow",
    purple: "WWN.colors.purple",
    blue: "WWN.colors.blue",
    orange: "WWN.colors.orange",
    white: "WWN.colors.white"
  },
  languages: [
    "Common",
    "Lawful",
    "Chaotic",
    "Neutral",
    "Bugbear",
    "Doppelgänger",
    "Dragon",
    "Dwarvish",
    "Elvish",
    "Gargoyle",
    "Gnoll",
    "Gnomish",
    "Goblin",
    "Halfling",
    "Harpy",
    "Hobgoblin",
    "Kobold",
    "Lizard Man",
    "Medusa",
    "Minotaur",
    "Ogre",
    "Orcish",
    "Pixie"
  ],
  tags: {
    melee: "WWN.items.Melee",
    missile: "WWN.items.Missile",
    SR: "WWN.items.SR",
    TH: "WWN.items.2H",
    AP: "WWN.items.AP",
    FX: "WWN.items.FX",
    L: "WWN.items.L",
    R: "WWN.items.R",
    LL: "WWN.items.LL",
    N: "WWN.items.N",
    PM: "WWN.items.PM",
    S: "WWN.items.S",
    SS: "WWN.items.SS",
    T: "WWN.items.T",
  },
  tag_images: {
    melee: "/systems/wwn/assets/melee.png",
    missile: "/systems/wwn/assets/missile.png",
    SR: "/systems/wwn/assets/slow_reload.png",
    TH: "/systems/wwn/assets/twohanded.png",
    AP: "/systems/wwn/assets/armor_piercing.png",
    FX: "/systems/wwn/assets/fixed.png",
    L: "/systems/wwn/assets/long.png",
    R: "/systems/wwn/assets/reload.png",
    LL: "/systems/wwn/assets/less_lethal.png",
    N: "/systems/wwn/assets/numerous.png",
    PM: "/systems/wwn/assets/precisely_murderous.png",
    S: "/systems/wwn/assets/subtle.png",
    SS: "/systems/wwn/assets/single_shot.png",
    T: "/systems/wwn/assets/throwable.png",
  },
  monster_saves: {
    0: {
      label: "Normal Human",
      d: 14,
      w: 15,
      p: 16,
      b: 17,
      s: 18
    },
    1: {
      label: "1-3",
      d: 12,
      w: 13,
      p: 14,
      b: 15,
      s: 16
    },
    4: {
      label: "4-6",
      d: 10,
      w: 11,
      p: 12,
      b: 13,
      s: 14
    },
    7: {
      label: "7-9",
      d: 8,
      w: 9,
      p: 10,
      b: 10,
      s: 12
    },
    10: {
      label: "10-12",
      d: 6,
      w: 7,
      p: 8,
      b: 8,
      s: 10
    },
    13: {
      label: "13-15",
      d: 4,
      w: 5,
      p: 6,
      b: 5,
      s: 8
    },
    16: {
      label: "16-18",
      d: 2,
      w: 3,
      p: 4,
      b: 3,
      s: 6
    },
    19: {
      label: "19-21",
      d: 2,
      w: 2,
      p: 2,
      b: 2,
      s: 4
    },
    22: {
      label: "22+",
      d: 2,
      w: 2,
      p: 2,
      b: 2,
      s: 2
    },
  }
};