import { systemPath } from "./config.js";

const preloadHandlebarsTemplates = async function () {
  const templatePaths = [
    // Actor V2 sheet parts
    systemPath("templates/actors/character/header.hbs"),
    systemPath("templates/actors/character/sheet-body.hbs"),
    systemPath("templates/actors/character/tab-main.hbs"),
    systemPath("templates/actors/character/tab-gear.hbs"),
    systemPath("templates/actors/character/tab-abilities.hbs"),
    systemPath("templates/actors/character/tab-notes.hbs"),
    systemPath("templates/actors/character/tab-effects.hbs"),
    systemPath("templates/actors/monster/header.hbs"),
    systemPath("templates/actors/monster/tab-attributes.hbs"),
    systemPath("templates/actors/monster/tab-spells.hbs"),
    systemPath("templates/actors/monster/tab-notes.hbs"),
    systemPath("templates/actors/monster/tab-effects.hbs"),
    // Actor partials
    systemPath("templates/actors/partials/character-header.hbs"),
    systemPath("templates/actors/partials/character-attributes-tab.hbs"),
    systemPath("templates/actors/partials/character-spells-tab.hbs"),
    systemPath("templates/actors/partials/character-inventory-tab.hbs"),
    systemPath("templates/actors/partials/actor-effects.hbs"),
    systemPath("templates/actors/partials/character-notes-tab.hbs"),
    systemPath("templates/actors/partials/monster-header.hbs"),
    systemPath("templates/actors/partials/monster-attributes-tab.hbs"),
    systemPath("templates/actors/partials/faction-assets.hbs"),
    systemPath("templates/actors/partials/ship-header.hbs"),
    systemPath("templates/actors/partials/ship-crew-list.hbs"),
    systemPath("templates/actors/partials/ship-attributes-tab.hbs"),
    systemPath("templates/actors/partials/ship-inventory-tab.hbs"),
    systemPath("templates/actors/partials/ship-notes-tab.hbs"),
    systemPath("templates/actors/partials/vehicle-header.hbs"),
    systemPath("templates/actors/partials/vehicle-inventory-tab.hbs"),
    // Actor sheet roots (faction, ship, vehicle)
    systemPath("templates/actors/faction-sheet.hbs"),
    systemPath("templates/actors/ship-sheet.hbs"),
    systemPath("templates/actors/vehicle-sheet-content.hbs"),
    // Item partials
    systemPath("templates/items/item-sheet-root.hbs"),
    systemPath("templates/items/partials/item-effects.hbs"),
    systemPath("templates/items/partials/description.hbs"),
    systemPath("templates/items/partials/item-header.hbs"),
    systemPath("templates/items/partials/item-tab-info.hbs"),
    systemPath("templates/items/partials/item-tab-description.hbs"),
    systemPath("templates/items/partials/item-tab-effects.hbs"),
    systemPath("templates/items/partials/weapon-header.hbs"),
    systemPath("templates/items/partials/weapon-tab-info.hbs"),
    systemPath("templates/items/partials/armor-header.hbs"),
    systemPath("templates/items/partials/armor-tab-info.hbs"),
    systemPath("templates/items/partials/ability-header.hbs"),
    systemPath("templates/items/partials/ability-tab-info.hbs"),
    systemPath("templates/items/partials/art-header.hbs"),
    systemPath("templates/items/partials/art-tab-info.hbs"),
    systemPath("templates/items/partials/spell-header.hbs"),
    systemPath("templates/items/partials/spell-tab-info.hbs"),
    systemPath("templates/items/partials/focus-header.hbs"),
    systemPath("templates/items/partials/focus-tab-description.hbs"),
    systemPath("templates/items/partials/fitting-header.hbs"),
    systemPath("templates/items/partials/fitting-tab-description.hbs"),
    systemPath("templates/items/partials/cargo-header.hbs"),
    systemPath("templates/items/partials/cargo-tab-description.hbs"),
    systemPath("templates/items/partials/shipweapon-header.hbs"),
    systemPath("templates/items/partials/shipweapon-tab-description.hbs"),
    systemPath("templates/items/partials/crewmember-header.hbs"),
    systemPath("templates/items/partials/crewmember-tab-description.hbs"),
    systemPath("templates/items/partials/asset-header.hbs"),
    systemPath("templates/items/partials/asset-tab-info.hbs"),
    systemPath("templates/items/partials/skill-header.hbs"),
    systemPath("templates/items/partials/skill-tab-main.hbs"),
    // Combat and apps
    systemPath("templates/apps/combat-set-groups.hbs"),
    systemPath("templates/apps/party-sheet.hbs"),
    systemPath("templates/apps/party-coin.hbs"),
    systemPath("templates/apps/party-xp.hbs"),
    systemPath("templates/apps/party-select.hbs"),
    // Dialogs
    systemPath("templates/actors/dialogs/adjust-currency.hbs"),
    systemPath("templates/actors/dialogs/lang-create.hbs"),
    systemPath("templates/actors/dialogs/modifiers-dialog.hbs"),
    systemPath("templates/actors/dialogs/tweaks-dialog.hbs"),
    systemPath("templates/actors/dialogs/faction-action.hbs"),
    systemPath("templates/actors/dialogs/faction-goal.hbs"),
    systemPath("templates/actors/dialogs/character-creation.hbs"),
    systemPath("templates/actors/dialogs/monster-saves.hbs"),
    systemPath("templates/items/dialogs/roll-skill.hbs"),
    systemPath("templates/items/dialogs/new-item.hbs"),
    systemPath("templates/items/dialogs/new-crew.hbs"),
    systemPath("templates/items/dialogs/select-asset-target.hbs"),
    systemPath("templates/items/entity-create.hbs"),
    // Chat
    systemPath("templates/chat/item-card.hbs"),
    systemPath("templates/chat/save-results.hbs"),
    systemPath("templates/chat/roll-creation.hbs"),
    systemPath("templates/chat/roll-result.hbs"),
    systemPath("templates/chat/roll-attack.hbs"),
    systemPath("templates/chat/roll-dialog.hbs"),
    systemPath("templates/chat/roll-treasure.hbs"),
    systemPath("templates/chat/apply-damage.hbs"),
    systemPath("templates/chat/asset-attack.hbs"),
    systemPath("templates/chat/asset-attack-def.hbs"),
    systemPath("templates/chat/faction-log.hbs"),
    systemPath("templates/chat/license.hbs"),
  ];
  return foundry.applications.handlebars.loadTemplates(templatePaths);
};

export default preloadHandlebarsTemplates;
